### ISSUE TITLE
make SHAP explanation figures hidden by default and show it by link click action

### ISSUE THREAD

**Issue by hussien** [DukeNgn/KGNet-Interface#12]

**Comment by DucNgn** [comment]
@kennguyen0303 Maybe we can have a toggle button for shap figures?

**Comment by kennguyen0303** [comment]
> @kennguyen0303 Maybe we can have a toggle button for shap figures?

Yeah for sure. 

I am also thinking about adding "see more..." To overview and Facts since they are quite long. 

@DukeNgn do you want to take this issue? I can take the "See more/see less" one

**Comment by DucNgn** [comment]
@kennguyen0303  Sure, sounds good
